# Labeler configuration for auto-labeling PRs

'documentation':
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

'dependencies':
  - changed-files:
    - any-glob-to-any-file: 
      - 'src/app/package.json'
      - 'src/app/package-lock.json'

'ci/cd':
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

'frontend':
  - changed-files:
    - any-glob-to-any-file: 
      - 'src/app/app/**/*.tsx'
      - 'src/app/app/**/*.jsx'
      - 'src/app/components/**'

'config':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/app/*.config.*'
      - 'src/app/tsconfig.json'
